# Generated by Django 4.2 on 2023-05-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_location_restaurantadministrator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="resume",
        ),
    ]
