# Generated by Django 4.2 on 2023-05-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_applicant_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_applicant",
            field=models.BooleanField(default=True),
        ),
    ]
