# Generated by Django 4.1 on 2023-05-01 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staffing_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantadministrator",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="loc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobposting",
                to="staffing_app.location",
            ),
        ),
        migrations.AddField(
            model_name="hiringmanager",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staffing_app.location"
            ),
        ),
        migrations.AddField(
            model_name="hiringmanager",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="staffing_app.applicant",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="hiring_manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="staffing_app.hiringmanager",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="staffing_app.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
