# Generated by Django 4.2 on 2023-05-04 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffing_app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="hiringmanager",
            name="location",
        ),
        migrations.RemoveField(
            model_name="hiringmanager",
            name="user",
        ),
        migrations.RemoveField(
            model_name="restaurantadministrator",
            name="location",
        ),
        migrations.RemoveField(
            model_name="restaurantadministrator",
            name="user",
        ),
    ]
