# Generated by Django 4.2 on 2023-05-04 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_location_restaurantadministrator_and_more"),
        (
            "staffing_app",
            "0003_remove_applicant_user_remove_hiringmanager_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="users.applicant",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="hiring_manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.hiringmanager"
            ),
        ),
        migrations.DeleteModel(
            name="Applicant",
        ),
        migrations.DeleteModel(
            name="HiringManager",
        ),
        migrations.DeleteModel(
            name="RestaurantAdministrator",
        ),
    ]
