# Generated by Django 4.2 on 2023-05-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffing_app", "0005_alter_jobposting_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="hiring_manager",
        ),
    ]
